### ISSUE TITLE
header

### ISSUE THREAD

**Issue by bplrdev** [charleywright/CheeseMenu#1]
Hi, thanks for sharing this project. I'd like to know how can I use the header.ytd. I already have the file, but I'm not sure where to put, and about what should be the name of the frames inside of it.  This `std::string delim = "\\";` supposed to be the root path of the DLL? So should I put the ytd next to it? No matter how I try it just shows either a white or a transparent header. 
Thanks in advance

**Comment by charleywright** [comment]
You can place your texture file (.ytd) anywhere, as long as you use that path in your code. I use the same folder as the DLL, as it is simpler for users and code.

> This std::string delim = "\\"; supposed to be the root path of the DLL?

No, that is just the path delimiter on Windows, the folder is found using the function `UIManager::GetModulePath`:
```c++
std::string path;
char buffer[MAX_PATH];
GetModuleFileNameA(module, buffer, MAX_PATH);
PathRemoveFileSpecA(buffer);
path = buffer;
return path;
````
That function returns the directory of the DLL file, which you can combine with delimiter and file name:
```c++
std::string fullPath = GetModulePath(g_Module) + "//"+ "header.ytd";
```
Then using that path you can load the texture file using `FileRegister` [sig](https://github.com/charleywright/CheeseMenu/blob/98dd7a9b3b424d0170fa707beadd0bfb5d701770/Code/UI/UIManager.cpp#L269).

As for naming the frames, I just used numbers because it is simple to loop over, although you can use whatever you want. If the texture is invalid, it will show as a blank white shape, so make sure the dictionary is the texture file without `.ytd` and the texture ID is correct. Beware of having extra "blank" bytes in your strings, as AFAIK they cause the game to crash.
